// Code generated by mockery v1.0.0. DO NOT EDIT.
package repository

import mock "github.com/stretchr/testify/mock"
import model "github.com/dfibrinogen/dfibrinogen-api/module/events"

// MockEventRepository is an auto generated mock type for the IEventRepository type
type MockEventRepository struct {
	mock.Mock
}

// CreateEvent provides a mock function with given fields: data
func (m *MockEventRepository) CreateEvent(data model.Event) (model.Event, error) {
	ret := m.Called(data)

	var r0 model.Event
	if rf, ok := ret.Get(0).(func(model.Event) model.Event); ok {
		r0 = rf(data)
	} else {
		r0 = ret.Get(0).(model.Event)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(model.Event) error); ok {
		r1 = rf(data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteEvent provides a mock function with given fields: id
func (m *MockEventRepository) DeleteEvent(id string) error {
	ret := m.Called(id)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FetchEventAll provides a mock function with given fields:
func (m *MockEventRepository) FetchEventAll() ([]model.Event, error) {
	ret := m.Called()

	var r0 []model.Event
	if rf, ok := ret.Get(0).(func() []model.Event); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Event)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FetchEventByID provides a mock function with given fields: id
func (m *MockEventRepository) FetchEventByID(id string) (model.Event, error) {
	ret := m.Called(id)

	var r0 model.Event
	if rf, ok := ret.Get(0).(func(string) model.Event); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(model.Event)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateEvent provides a mock function with given fields: data
func (m *MockEventRepository) UpdateEvent(data model.Event) (model.Event, error) {
	ret := m.Called(data)

	var r0 model.Event
	if rf, ok := ret.Get(0).(func(model.Event) model.Event); ok {
		r0 = rf(data)
	} else {
		r0 = ret.Get(0).(model.Event)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(model.Event) error); ok {
		r1 = rf(data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
